spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      
mongodb:
  primary:
    host: ${mongo.host}
    port: ${mongo.port}
    database: ${mongo.dbname}